/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Nhung;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ADMIN
 */
public class QuanLyLsXuatVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyLsXuatVien
     */
    public QuanLyLsXuatVien() {
        initComponents();
        load_LS();
    }
    Connection con;
    private void load_LS(){
        try {
            tbLSXV.removeAll(); 
            con = BTL.Connect.KetnoiDB();
            String sql = "SELECT * FROM LichSuXuatVien";
            Statement st = con.createStatement(); 
            ResultSet rs = st.executeQuery(sql); 
            String[] tieude = {"Mã xuất viện", "Mã bệnh nhân", "Ngày xuất viện", "Kết quả điều trị","Ghi chú"};
            DefaultTableModel tb = new DefaultTableModel(tieude, 0);

            while (rs.next()) {
                Vector<String> v = new Vector<>();
                v.add(rs.getString("MaXuatVien")); 
                v.add(rs.getString("MaBenhNhan")); 
                v.add(rs.getDate("NgayXuatVien") != null ? rs.getDate("NgayXuatVien").toString() : ""); // Ngày nhập viện
                v.add(rs.getString("KetQuaDieuTri"));
                v.add(rs.getString("GhiChu")); 
                tb.addRow(v); 
            }
            tbLSXV.setModel(tb); 
            con.close(); 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        xuatExcel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tk_ma = new javax.swing.JTextField();
        timkiem = new javax.swing.JButton();
        nhapExcel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mxv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mbn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ngayxv = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        kqdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLSXV = new javax.swing.JTable();
        them = new javax.swing.JButton();
        capnhat = new javax.swing.JButton();
        xoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ LỊCH SỬA XUẤT VIỆN");

        xuatExcel.setText("Xuất Excel");
        xuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatExcelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setText("Mã xuất viện:");

        tk_ma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tk_maMouseClicked(evt);
            }
        });
        tk_ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk_maActionPerformed(evt);
            }
        });
        tk_ma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tk_maKeyReleased(evt);
            }
        });

        timkiem.setText("Tìm Kiếm");
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tk_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(timkiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tk_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timkiem))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        nhapExcel.setText("Nhập Excel");
        nhapExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapExcelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel3.setText("Mã xuất viện:");

        jLabel4.setText("Mã bệnh nhân:");

        mbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbnActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày xuất viện:");

        ngayxv.setDateFormatString("yyyy-MM-dd");

        jLabel6.setText("Kết quả điều trị:");

        jLabel7.setText("Ghi chú:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mbn, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(mxv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngayxv, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kqdt, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                            .addComponent(gc))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ngayxv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mxv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kqdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbLSXV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã xuất viện", "Mã bệnh nhân", "Ngày xuất viện", "Kết quả điều trị", "Ghi chú"
            }
        ));
        tbLSXV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLSXVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLSXV);

        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        capnhat.setText("Cập nhật");
        capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatActionPerformed(evt);
            }
        });

        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(them)
                                .addGap(18, 18, 18)
                                .addComponent(capnhat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xuatExcel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nhapExcel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(thoat))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(capnhat)
                    .addComponent(xoa)
                    .addComponent(thoat)
                    .addComponent(nhapExcel)
                    .addComponent(xuatExcel))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed
            // TODO add your handling code here:
             String searchTerm = tk_ma.getText().trim(); // Lấy mã xuất viện từ JTextField

        if (searchTerm.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã xuất viện để tìm kiếm!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return; // Dừng lại nếu mã xuất viện trống
        }

        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            con = BTL.Connect.KetnoiDB(); // Kết nối cơ sở dữ liệu
            String sql = "SELECT * FROM LichSuXuatVien WHERE MaXuatVien = ?"; // Câu lệnh SQL tìm theo MaXuatVien
            pst = con.prepareStatement(sql);
            pst.setString(1, searchTerm); // Đưa mã xuất viện vào câu truy vấn

            rs = pst.executeQuery(); // Thực hiện câu truy vấn

            if (rs.next()) {
                mxv.setText(rs.getString("MaXuatVien")); // Hiển thị mã xuất viện
                mbn.setText(rs.getString("MaBenhNhan"));  // Hiển thị mã bệnh nhân
                Date ngayXuatVien = rs.getDate("NgayXuatVien"); // Hiển thị ngày xuất viện
                if (ngayXuatVien != null) {
                    ngayxv.setDate(ngayXuatVien);
                }
                kqdt.setText(rs.getString("KetQuaDieuTri")); // Hiển thị kết quả điều trị
                gc.setText(rs.getString("GhiChu")); // Hiển thị ghi chú
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy hồ sơ xuất viện với mã đã cho!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi SQL: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Đóng các tài nguyên (ResultSet, PreparedStatement, Connection)
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_timkiemActionPerformed

    private void mbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbnActionPerformed

    private void tbLSXVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLSXVMouseClicked
        // TODO add your handling code here:
        int i = tbLSXV.getSelectedRow();
        if (i != -1) {
            DefaultTableModel model = (DefaultTableModel) tbLSXV.getModel();
            mxv.setText(model.getValueAt(i, 0).toString());
            mbn.setText(model.getValueAt(i, 1).toString());
            String ngay = model.getValueAt(i, 2).toString();
            java.util.Date ngaysinh;
            try {
                ngaysinh = new SimpleDateFormat("yyyy-MM-dd").parse(ngay);
                ngayxv.setDate(ngaysinh);
            } catch (Exception e) {
                e.printStackTrace();
            }
            kqdt.setText(model.getValueAt(i, 3).toString());
            gc.setText(model.getValueAt(i, 4).toString());

            mxv.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hồ sơ để xem thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_tbLSXVMouseClicked
     public void xoatrang(){
            mxv.setText("");
            mbn.setText("");
            ngayxv.setDate(null);
            kqdt.setText("");
            gc.setText("");
    }
    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        String maxv = this.mxv.getText().trim();
        String mabn = mbn.getText().trim();
        Date ngay= new Date(ngayxv.getDate().getTime());
        if (ngayxv.getDate() != null) {
            ngay = new Date(ngayxv.getDate().getTime());
        }
        String kq = kqdt.getText().trim();
        String gchu = gc.getText().trim();
        
        if (maxv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã xuất viện không được để trống.");
            mxv.requestFocus();
            return;
        }

        if (mabn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã bệnh nhân không được để trống.");
            mbn.requestFocus();
            return;
        }

        if (ngay == null) {
            JOptionPane.showMessageDialog(this, "Ngày xuất viện không được để trống.");
            ngayxv.requestFocus();
            return;
        }

        if (kq.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kết quả điều trị không được để trống.");
            kqdt.requestFocus();
            return;
        }

        if (gchu.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ghi chú không được để trống.");
            gc.requestFocus();
            return;
        }
        
        try {
            con = BTL.Connect.KetnoiDB();
            // Kiểm tra xem kết nối có null không
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Không thể kết nối đến cơ sở dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; // Thoát khỏi phương thức nếu không kết nối được
            }
            String sql = "INSERT INTO LichSuXuatVien " +
            "VALUES ('"+ maxv +"', '" + mabn + "', '" + ngay +"', N'"+kq+"', N'"+gchu+"')";

            // Tạo Statement
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Lịch sử xuất viện đã được thêm thành công!");
            st.close();
            con.close();
            load_LS();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_themActionPerformed

    private void capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatActionPerformed
         String maxv = mxv.getText().trim();
    String mabn = mbn.getText().trim();
    
    // Lấy giá trị ngày từ JDateChooser (ngayxv)
    java.util.Date utilDate = ngayxv.getDate(); // Lấy ngày từ JDateChooser, trả về java.util.Date

    // Kiểm tra nếu utilDate không null để tránh lỗi NullPointerException
    if (utilDate == null) {
        JOptionPane.showMessageDialog(this, "Phải nhập ngày xuất viện!");
        return;
    }
    
    // Chuyển đổi sang java.sql.Date để sử dụng với cơ sở dữ liệu
    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

    if (maxv.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Phải nhập mã xuất viện!");
        return;
    }
    if (mabn.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Phải nhập mã bệnh nhân!");
        return;
    }
    String kq = kqdt.getText().trim();
    if (kq.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Phải nhập kết quả điều trị!");
        return;
    }

    String gchu = gc.getText().trim();
    if (gchu.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Phải nhập ghi chú!");
        return;
    }

    try {
        con = BTL.Connect.KetnoiDB();
        
        // Cập nhật dữ liệu sử dụng PreparedStatement
        String sql = "UPDATE LichSuXuatVien SET " +
                     "MaBenhNhan = ?, " +
                     "NgayXuatVien = ?, " +
                     "KetQuaDieuTri = ?, " +
                     "GhiChu = ? " +
                     "WHERE MaXuatVien = ?";

        // Sử dụng PreparedStatement để tránh SQL Injection
        try (PreparedStatement pstmt = con.prepareStatement(sql)) {
            pstmt.setString(1, mabn);
            pstmt.setDate(2, sqlDate);  // Sử dụng java.sql.Date
            pstmt.setString(3, kq);
            pstmt.setString(4, gchu);
            pstmt.setString(5, maxv);

            int rowsUpdated = pstmt.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Hồ sơ xuất viện đã được cập nhật thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy hồ sơ với mã HS đã cho!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }

        load_LS(); // Gọi phương thức để tải lại dữ liệu
        xoatrang();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Cập nhật không thành công", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Đảm bảo đóng kết nối nếu nó chưa được đóng
        if (con != null) {
            try {
                con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    }//GEN-LAST:event_capnhatActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        String maxv = mxv.getText().trim();
    
        // Kiểm tra xem mã hồ sơ có được nhập hay không
        if (maxv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã hồ sơ để xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection con = null;
        PreparedStatement deleteStmt = null;

        try {
            con = BTL.Connect.KetnoiDB();

            // Tạo câu lệnh SQL để xóa
            String sql = "DELETE FROM LichSuXuatVien WHERE MaXuatVien = ?";
            deleteStmt = con.prepareStatement(sql);
            deleteStmt.setString(1, maxv);

            // Thực thi câu lệnh xóa
            int rowsDeleted = deleteStmt.executeUpdate();

            // Kiểm tra nếu xóa thành công
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Hồ sơ xuất viện đã được xóa thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy hồ sơ với mã HS đã cho!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }

            // Tải lại dữ liệu
            load_LS();
            // Clear the input fields
            mxv.setText("");
            mbn.setText("");
            ngayxv.setDate(null);
            kqdt.setText("");
            gc.setText("");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi SQL: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Đóng kết nối và tài nguyên
            try {
                if (deleteStmt != null) deleteStmt.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_xoaActionPerformed

    private void tk_maKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tk_maKeyReleased
        // TODO add your handling code here:
        try {
           String mxv = tk_ma.getText().trim();  // Mã xuất viện

        // Kết nối đến cơ sở dữ liệu
        con = BTL.Connect.KetnoiDB();
        Statement st = con.createStatement();

        // Xây dựng câu lệnh SQL cho tìm kiếm
        String sql = "SELECT * FROM LichSuXuatVien WHERE MaXuatVien LIKE '%" + mxv + "%'";

        // Thực hiện truy vấn
        ResultSet rs = st.executeQuery(sql);
        String[] tieude = {"Mã xuất viện", "Mã bệnh nhân", "Ngày xuất viện", "Kết quả điều trị", "Ghi chú"};
        DefaultTableModel tb = new DefaultTableModel(tieude, 0);

        // Duyệt qua kết quả và thêm vào bảng
        while (rs.next()) {
            Vector<String> v = new Vector<>();
            v.add(rs.getString("MaXuatVien"));         
            v.add(rs.getString("MaBenhNhan"));        
            v.add(rs.getString("NgayXuatVien"));       
            v.add(rs.getString("KetQuaDieuTri"));   
            v.add(rs.getString("GhiChu"));  
            tb.addRow(v);
        }

        // Gán model mới cho bảng
        tbLSXV.setModel(tb);

        // Đóng kết nối
        con.close();
       } catch (Exception e) {
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "Tìm kiếm không thành công");
       }
    }//GEN-LAST:event_tk_maKeyReleased

    private void tk_maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk_maActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk_maActionPerformed

    private static CellStyle DinhDangHeader(XSSFSheet sheet){
    XSSFFont font = sheet.getWorkbook().createFont();
    font.setFontName("Times New Roman");
    font.setBold(true);
    font.setFontHeightInPoints((short) 12); // kích thước font
    font.setColor(IndexedColors.WHITE.getIndex()); // màu chữ

    // Tạo CellStyle
    CellStyle cellStyle = sheet.getWorkbook().createCellStyle();
    cellStyle.setFont(font);
    cellStyle.setAlignment(HorizontalAlignment.CENTER);
    cellStyle.setVerticalAlignment(VerticalAlignment.TOP);

    cellStyle.setFillForegroundColor(IndexedColors.DARK_GREEN.getIndex());
    cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
    cellStyle.setBorderBottom(BorderStyle.THIN);
    cellStyle.setWrapText(true);

    return cellStyle;
    }
    private void xuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatExcelActionPerformed
        // TODO add your handling code here:
        try {
          // Tạo workbook và sheet
    XSSFWorkbook workbook = new XSSFWorkbook();
    XSSFSheet spreadsheet = workbook.createSheet("Khoa");

    // Tạo tiêu đề cho bảng
    XSSFRow row = spreadsheet.createRow(2); // Dòng thứ 3 (chỉ số 2)
    Cell cell = row.createCell(0);
    cell.setCellValue("DANH SÁCH LỊCH SỬ XUẤT VIỆN");

    // Tạo dòng tiêu đề cột
    CellStyle cellStyle_Head = DinhDangHeader(spreadsheet);
    row = spreadsheet.createRow(3); // Dòng thứ 4 (chỉ số 3)
    
    // Thiết lập các tiêu đề cột
    String[] headers = {"Mã xuất viện", "Mã bệnh nhân", "Ngày xuất viện", "Kết quả điều trị", "Ghi chú"};
    for (int i = 0; i < headers.length; i++) {
        cell = row.createCell(i);
        cell.setCellStyle(cellStyle_Head);
        cell.setCellValue(headers[i]);
    }

    // Kết nối đến cơ sở dữ liệu
    con = BTL.Connect.KetnoiDB();
    String sql = "SELECT * FROM lichsuxuatvien";
    
    // Thay đổi PreparedStatement
    PreparedStatement st = con.prepareStatement(sql, 
    ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet rs = st.executeQuery();

    // Kiểm tra có dữ liệu trả về
    if (!rs.next()) {
        System.out.println("Không có dữ liệu nào để xuất.");
        return;
    }
    
    // Trở về đầu ResultSet
    rs.beforeFirst();

    // Đổ dữ liệu từ ResultSet vào các ô trong Excel
    ResultSetMetaData rsmd = rs.getMetaData();
    int tongsocot = rsmd.getColumnCount();

    // Định dạng ô chứa dữ liệu
    CellStyle cellStyle_data = workbook.createCellStyle();
    cellStyle_data.setBorderLeft(BorderStyle.THIN);
    cellStyle_data.setBorderRight(BorderStyle.THIN);
    cellStyle_data.setBorderBottom(BorderStyle.THIN);

    int i = 0;
    while (rs.next()) {
        row = spreadsheet.createRow(4 + i); // Bắt đầu từ dòng 5

        // Điền dữ liệu vào các ô
        for (int j = 1; j <= tongsocot; j++) {
            cell = row.createCell(j - 1);
            cell.setCellStyle(cellStyle_data);
            cell.setCellValue(rs.getString(j)); // Đổ dữ liệu từ ResultSet vào ô
        }
        i++;
    }

    // Hiệu chỉnh độ rộng của cột
    for (int col = 0; col < tongsocot; col++) {
        spreadsheet.autoSizeColumn(col);
    }

    // Xuất file Excel
    File f = new File("C:\\Users\\Admin\\Documents\\NetBeansProjects\\hosobenhnhann\\src\\main\\java\\Nhung\\DanhSachChanDoan.xlsx");
    FileOutputStream out = new FileOutputStream(f);
    workbook.write(out);
    out.close();
    
    // Đóng các đối tượng liên quan
    rs.close();
    st.close();
    con.close();  
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_xuatExcelActionPerformed
    private void ReadExcel(String tenFilepath){
        try {
            String tenfilepath = null;
            FileInputStream fis = new FileInputStream(tenfilepath);
            XSSFWorkbook wb = new XSSFWorkbook(fis);
            XSSFSheet sheet = wb.getSheetAt(0); // Lấy sheet đầu tiên
            Iterator<Row> itr = sheet.iterator();
            int row_count = 0;

            while (itr.hasNext()) {
                Row row = itr.next();
                if (row_count > 0) { // Bỏ qua dòng tiêu đề
                    String mxv = "";
                    Cell cell1 = row.getCell(0);
                    if (cell1 != null) {
                        if (cell1.getCellType() == CellType.STRING) {
                            mxv = cell1.getStringCellValue().trim();
                        } else if (cell1.getCellType() == CellType.NUMERIC) {
                            mxv = String.valueOf((int) cell1.getNumericCellValue());
                        }
                    }

                    // Kiểm tra xem mbn có phải là chuỗi rỗng không
                    if (mxv.isEmpty()) {
                        row_count++;
                        continue; // Bỏ qua dòng này
                    }

                    String mbn = "";
                    Cell cell2 = row.getCell(1);
                    if (cell2 != null) {
                        if (cell2.getCellType() == CellType.STRING) {
                            mbn = cell2.getStringCellValue().trim();
                        } else if (cell2.getCellType() == CellType.NUMERIC) {
                            mbn = String.valueOf(cell2.getNumericCellValue()).trim();
                        }
                    }

                    String nxv = "";
                    Cell cell3 = row.getCell(2);
                    if (cell3 != null) {
                        if (cell3.getCellType() == CellType.STRING) {
                            nxv = cell3.getStringCellValue().trim();
                        } else if (cell3.getCellType() == CellType.NUMERIC) {
                            nxv= new SimpleDateFormat("yyyy-MM-dd").format(cell3.getDateCellValue());
                        }
                    }

                    String kqdt = "";
                    Cell cell4 = row.getCell(3);
                    if (cell4 != null) {
                        if (cell4.getCellType() == CellType.STRING) {
                            kqdt = cell4.getStringCellValue().trim();
                        } else if (cell4.getCellType() == CellType.NUMERIC) {
                            kqdt = String.valueOf(cell4.getNumericCellValue()).trim();
                        }
                    }

                    String gc = "";
                    Cell cell5 = row.getCell(4);
                    if (cell5 != null) {
                        if (cell5.getCellType() == CellType.STRING) {
                            gc = cell5.getStringCellValue().trim();
                        } else if (cell5.getCellType() == CellType.NUMERIC) {
                           gc = String.valueOf(cell5.getNumericCellValue()).trim();
                        }
                    }

                   
                    // Gọi phương thức thêm bệnh nhân
                    Themlichsuxuatvien(mxv, mbn, nxv, kqdt, gc);
                }
                row_count++;
            }
            JOptionPane.showMessageDialog(this, "Thêm bệnh nhân bằng file thành công");
            load_LS();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    private void nhapExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapExcelActionPerformed
        // TODO add your handling code here:
          try {
        JFileChooser fc = new JFileChooser();
        int lc = fc.showOpenDialog(this);
        if (lc == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            String tenfile = file.getName();
            if (tenfile.endsWith(".xlsx")) { // Kiểm tra file có đuôi .xlsx
                ReadExcel(file.getPath());
            } else {
                JOptionPane.showMessageDialog(this, "Phải chọn file excel có định dạng .xlsx", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không có file nào được chọn", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi mở file: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // In stack trace ra console để kiểm tra
        }
    }//GEN-LAST:event_nhapExcelActionPerformed

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_thoatActionPerformed

    private void tk_maMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tk_maMouseClicked
        xoatrang();
    }//GEN-LAST:event_tk_maMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyLsXuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyLsXuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyLsXuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyLsXuatVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyLsXuatVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capnhat;
    private javax.swing.JTextField gc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kqdt;
    private javax.swing.JTextField mbn;
    private javax.swing.JTextField mxv;
    private com.toedter.calendar.JDateChooser ngayxv;
    private javax.swing.JButton nhapExcel;
    private javax.swing.JTable tbLSXV;
    private javax.swing.JButton them;
    private javax.swing.JButton thoat;
    private javax.swing.JButton timkiem;
    private javax.swing.JTextField tk_ma;
    private javax.swing.JButton xoa;
    private javax.swing.JButton xuatExcel;
    // End of variables declaration//GEN-END:variables

    private void Themlichsuxuatvien(String mxv, String mbn, String nxv, String kqdt, String gc) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
