/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package KienDuPhong;

import KienDuPhong.quanlykhoa;
import KienDuPhong.lichlamviec;
import KienDuPhong.Lichsudieutri;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class Quanlykien extends javax.swing.JInternalFrame {

    /**
     * Creates new form Quanlykien
     */
    public Quanlykien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btlsdt = new javax.swing.JButton();
        btllv = new javax.swing.JButton();
        btk = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(561, 562));

        btlsdt.setText("Lịch sử điều trị");
        btlsdt.setPreferredSize(new java.awt.Dimension(187, 187));
        btlsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlsdtActionPerformed(evt);
            }
        });

        btllv.setText("Lịch làm việc");
        btllv.setPreferredSize(new java.awt.Dimension(187, 187));
        btllv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btllvActionPerformed(evt);
            }
        });

        btk.setText("Quản lý khoa");
        btk.setPreferredSize(new java.awt.Dimension(187, 187));
        btk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btllv, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(btk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlsdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btllv, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btk, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btlsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlsdtActionPerformed
        // TODO add your handling code here:
        Lichsudieutri dt = new Lichsudieutri();
        dt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dt.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            }
        });
        dt.setVisible(true);
    }//GEN-LAST:event_btlsdtActionPerformed

    private void btllvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btllvActionPerformed
        // TODO add your handling code here:
        lichlamviec llv = new lichlamviec();
        llv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        llv.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            }
        });
        llv.setVisible(true);
    }//GEN-LAST:event_btllvActionPerformed

    private void btkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkActionPerformed
        // TODO add your handling code here:
        quanlykhoa qlk = new quanlykhoa();
        qlk.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        qlk.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            }
        });
        qlk.setVisible(true);
    }//GEN-LAST:event_btkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btk;
    private javax.swing.JButton btllv;
    private javax.swing.JButton btlsdt;
    // End of variables declaration//GEN-END:variables
}
