/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package QLDT;

import java.awt.event.WindowAdapter;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Admin
 */
public class Quanlydieutri extends javax.swing.JInternalFrame {

    /**
     * Creates new form Quanlydieutri
     */
    public Quanlydieutri() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvyt = new javax.swing.JButton();
        btdt = new javax.swing.JButton();
        btqtqldt = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(561, 562));

        btnvyt.setText("Nhân viên y tế");
        btnvyt.setPreferredSize(new java.awt.Dimension(187, 187));
        btnvyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvytActionPerformed(evt);
            }
        });

        btdt.setText("Đơn thuốc");
        btdt.setPreferredSize(new java.awt.Dimension(187, 187));
        btdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdtActionPerformed(evt);
            }
        });

        btqtqldt.setText("Quản lý quá trình điều trị");
        btqtqldt.setPreferredSize(new java.awt.Dimension(187, 187));
        btqtqldt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btqtqldtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btdt, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(btqtqldt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnvyt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btdt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btqtqldt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvyt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvytActionPerformed
        // TODO add your handling code here:
        Nhanvienyte nvyt = new Nhanvienyte();
        nvyt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nvyt.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            }
        });
        nvyt.setVisible(true);
    }//GEN-LAST:event_btnvytActionPerformed

    private void btdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdtActionPerformed
        // TODO add your handling code here:
        Donthuoc dt = new Donthuoc();
        dt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dt.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            }
        });
        dt.setVisible(true);
    }//GEN-LAST:event_btdtActionPerformed

    private void btqtqldtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btqtqldtActionPerformed
        // TODO add your handling code here:
        Quanliquatrinhdieutri qlqtdt = new Quanliquatrinhdieutri();
        qlqtdt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        qlqtdt.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            }
        });
        qlqtdt.setVisible(true);
    }//GEN-LAST:event_btqtqldtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdt;
    private javax.swing.JButton btnvyt;
    private javax.swing.JButton btqtqldt;
    // End of variables declaration//GEN-END:variables

    private void addWindowListener(WindowAdapter windowAdapter) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
